### PR TITLE
Fix deployment strategy

### LINKED ISSUE #152: Multiple data updater plant pods while upgrading version
When updating astarte version multiple DUP pods might be alive and consuming from the same set of queues, this is not a correct behavior and might cause out of order message processing and properties inconsistencies. 

```
$ kubectl get pods -n astarte
astarte-data-updater-plant-6f5685d44b-cz29s        0/1     Terminating         2          22m
astarte-data-updater-plant-77bbb8d965-bbffc        1/1     Running             0          39s
[...]
```
All DUP pods should be stopped before starting new DUP pod.

### PR DESCRIPTION
**Pull request by matt-mazzucato**
The default deployment strategy for DUP is "Recreate": it prevents
the consumption of messages from the same queue, thus avoiding
out of order message processing and properties inconsistencies.
Fix #152

### CODE REVIEW

File: pkg/controller/astarte/reconcile/astarte_dashboard.go [hunk 1]
```diff
@@ -102,7 +102,7 @@ func EnsureAstarteDashboard(cr *apiv1alpha1.Astarte, dashboard apiv1alpha1.Astar
 		Selector: &metav1.LabelSelector{
 			MatchLabels: matchLabels,
 		},
-		Strategy: getDeploymentStrategyForClusteredResource(cr, dashboard.AstarteGenericClusteredResource),
+		Strategy: getDeploymentStrategyForClusteredResource(cr, dashboard.AstarteGenericClusteredResource, "dashboard"),
```
Comment (rbino) [inline pkg/controller/astarte/reconcile/astarte_dashboard.go:105]: I think `"dashboard"` should be a `apiv1alpha1.Dashboard` instead

File: pkg/controller/astarte/reconcile/utils.go [hunk 2]
```diff
@@ -390,10 +390,15 @@ func getImageForClusteredResource(defaultImageName, defaultImageTag string, reso
 	return image
 }
 
-func getDeploymentStrategyForClusteredResource(cr *apiv1alpha1.Astarte, resource apiv1alpha1.AstarteGenericClusteredResource) appsv1.DeploymentStrategy {
+func getDeploymentStrategyForClusteredResource(cr *apiv1alpha1.Astarte, resource apiv1alpha1.AstarteGenericClusteredResource, component apiv1alpha1.AstarteComponent) appsv1.DeploymentStrategy {
 	if resource.DeploymentStrategy != nil {
 		return *resource.DeploymentStrategy
 	}
+	if component.DashedString() == "data-updater-plant" || component.DashedString() == "flow" {
```
Comment (drf) [inline pkg/controller/astarte/reconcile/utils.go:397]: 1. Don't use literals, use the correct constants
2. This is wrong on several levels, `cr.Spec.DeploymentStrategy` should become a pointer, then:

* if it's `nil`, then this logic is correct and you should return Recreate or RollingUpdate
* if it's not nil, you should return its value

If you don't do this, you're overriding the user's choices

File: pkg/controller/astarte/reconcile/utils.go [hunk 3]
```diff
@@ -390,10 +390,15 @@ func getImageForClusteredResource(defaultImageName, defaultImageTag string, reso
...
+		return appsv1.DeploymentStrategy{
+			Type: "Recreate",
```
Comment (drf) [inline pkg/controller/astarte/reconcile/utils.go:399]: Again never use literals

**Review by drf — CHANGES_REQUESTED** [review]
Some work to do

File: pkg/controller/astarte/reconcile/utils.go (hunk 2 above)
Comment (rbino) [inline pkg/controller/astarte/reconcile/utils.go:397]: switch on the component itself instead of the dashed string
```go
switch component {
case apiv1alpha1.DataUpdaterPlant:
  ...
}
```

**Review by rbino — CHANGES_REQUESTED** [review]

File: pkg/controller/astarte/reconcile/utils.go [hunk 4]
```diff
@@ -390,9 +390,14 @@ func getImageForClusteredResource(defaultImageName, defaultImageTag string, reso
 	return image
 }
 
-func getDeploymentStrategyForClusteredResource(cr *apiv1alpha1.Astarte, resource apiv1alpha1.AstarteGenericClusteredResource) appsv1.DeploymentStrategy {
+func getDeploymentStrategyForClusteredResource(cr *apiv1alpha1.Astarte, resource apiv1alpha1.AstarteGenericClusteredResource, component apiv1alpha1.AstarteComponent) *appsv1.DeploymentStrategy {
```
Comment (drf) [inline pkg/controller/astarte/reconcile/utils.go:393]: Nope. Don't return a pointer, you're overcomplicating the code. Keep the pointer math hidden behind this function.

File: pkg/controller/astarte/reconcile/utils.go [hunk 5]
```diff
@@ -390,9 +390,14 @@ func getImageForClusteredResource(defaultImageName, defaultImageTag string, reso
...
 	if resource.DeploymentStrategy != nil {
-		return *resource.DeploymentStrategy
+		return resource.DeploymentStrategy
+	}
+	if component == apiv1alpha1.DataUpdaterPlant && resource.DeploymentStrategy == nil {
```
Comment (drf) [inline pkg/controller/astarte/reconcile/utils.go:397]: So Flow shouldn't be part of this strategy?

**Review by drf — CHANGES_REQUESTED** [review]
Pointer math is broken, simplify it

File: pkg/controller/astarte/reconcile/utils.go (hunk 5 above)
Comment (matt-mazzucato) [reply pkg/controller/astarte/reconcile/utils.go:397]: Flow was introduced since 1.0. It will be handled in a dedicated PR targeting 1.0.

File: pkg/controller/astarte/reconcile/utils.go [hunk 6]
```diff
@@ -390,11 +390,16 @@ func getImageForClusteredResource(defaultImageName, defaultImageTag string, reso
...
 	if resource.DeploymentStrategy != nil {
 		return *resource.DeploymentStrategy
 	}
-	return cr.Spec.DeploymentStrategy
+	if component == apiv1alpha1.DataUpdaterPlant && resource.DeploymentStrategy == nil {
+		return appsv1.DeploymentStrategy{
+			Type: appsv1.RecreateDeploymentStrategyType,
+		}
+	}
+	return *cr.Spec.DeploymentStrategy
```
Comment (drf) [inline pkg/controller/astarte/reconcile/utils.go:402]: Wait. There is a huge problem here, I honestly have no idea what happens when DeploymentStrategy is nil, and tests are passing because tests *are* forcing `Recreate`. You probably want to have a switch statement which returns the value IF it's not nil, or one of the two strategies otherwise.

**Review by drf — CHANGES_REQUESTED** [review]
Think I found a blocker

File: pkg/controller/astarte/reconcile/utils.go [hunk 7]
```diff
@@ -390,11 +390,22 @@ func getImageForClusteredResource(defaultImageName, defaultImageTag string, reso
...
 }
 
-func getDeploymentStrategyForClusteredResource(cr *apiv1alpha1.Astarte, resource apiv1alpha1.AstarteGenericClusteredResource) appsv1.DeploymentStrategy {
-	if resource.DeploymentStrategy != nil {
+func getDeploymentStrategyForClusteredResource(cr *apiv1alpha1.Astarte, resource apiv1alpha1.AstarteGenericClusteredResource, component apiv1alpha1.AstarteComponent) appsv1.DeploymentStrategy {
+
+	switch {
+	case resource.DeploymentStrategy != nil:
 		return *resource.DeploymentStrategy
+	case component == apiv1alpha1.DataUpdaterPlant && resource.DeploymentStrategy == nil:
```
Comment (drf) [inline pkg/controller/astarte/reconcile/utils.go:398]: The `resource.DeploymentStrategy == nil` is redundant if you place the `cr.Spec.DeploymentStrategy != nil` case above this

**Review by drf — CHANGES_REQUESTED** [review]
small optimization

**Review by bettio — APPROVED** [review]

**Review by rbino — APPROVED** [review]
